### ISSUE TITLE
Example 1  Put anomaly scores in a list is giving error

### ISSUE THREAD

**Issue by ashish-r** [linkedin/luminol#10]
getting `ValueError: (22, 'Invalid argument')` 
in line: `t_str = time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(timestamp))` 

actually, the error is due to value of timestamp provided as argument in `time.localtime(timestamp)`

using _SAR-device.sdb.await.csv_ provided in **luminol/demo/src/static/data/**. 

Using Python 2.7. Please Help.

**Comment by brennv** [comment]
The example is missing `import time`. The example is a bit clearer without the time conversion: #15
