### ISSUE TITLE
Python 3.6 doesn't run your examples

### ISSUE THREAD

**Issue by sjjpo2002** [linkedin/luminol#32]
Looks like the support for Python 3 is not completely developed yet. With Python 3.6 the examples you have don't run:

`from luminol.anomaly_detector import AnomalyDetector`

What's the easy fix for this?

**Comment by brennv** [comment]
Could you try this example:

```
from luminol.anomaly_detector import AnomalyDetector

ts = {0: 0, 1: 0.5, 2: 1, 3: 1, 4: 1, 5: 0, 6: 0, 7: 0, 8: 0}
my_detector = AnomalyDetector(ts)
score = my_detector.get_all_scores()
for timestamp, value in score.iteritems():
    print(timestamp, value)
```

We're working on an update to the readme with #30. You can preview it [here](https://github.com/brennv/luminol3/blob/readme/README.md#example).

**Comment by ollieglass** [comment]
Your example throws an error for me, using version 0.4 from github on Python 3.6

```python
from luminol.anomaly_detector import AnomalyDetector

ts = {0: 0, 1: 0.5, 2: 1, 3: 1, 4: 1, 5: 0, 6: 0, 7: 0, 8: 0}
my_detector = AnomalyDetector(ts)

TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

**Comment by brennv** [comment]
@ollieglass If you `pip freeze` does it show `luminol==0.4`?

**Comment by ollieglass** [comment]
Yes

**Comment by brennv** [comment]
Hmmm, I'm not able to reproduce this but it seems this would be the line that results in the error:
https://github.com/linkedin/luminol/blob/master/src/luminol/anomaly_detector.py#L120

Could we get the full traceback of the error message? As well as any details if this is on OSX/Linux/Windows?

**Comment by ollieglass** [comment]
I just reinstalled it, tried the example again and it's working. I'm really sorry, the error is almost certainly at my end.

**Comment by brennv** [comment]
No worries :) the install process is a bit jenky at the moment... hopefully we can get a new pypi release going soon. #35

**Comment by brennv** [comment]
I think this issue can be closed now that pypi has been updated
