### ISSUE TITLE
Citing luminol

### ISSUE THREAD

**Issue by Fisch-Alex** [linkedin/luminol#42]
Hi, 

I would like to cite luminol for an academic publication, but was unable to find a list of authors other than "Naarad Developers". Would it be possible to let me know how you would you like me to cite the package?

Thank you very much in advance. 

Best wishes, 
Alex

**Comment by RiteshMaheshwari** [comment]
Hi Alex,

Here are the authors:
Ritesh Maheshwari, Yang Yang, Ruixuan Hou, Baolei Li, Liang Zhang

Thanks,
Ritesh
