### ISSUE TITLE
problem with import 

### ISSUE THREAD

**Issue by guyoh** [linkedin/luminol#9]
I have install the package via pip (using python 2.7.12)
When I import the module luminol , it lacks all of the basic functions. I've atached a print screen.
Can you help me ?
![image](https://cloud.githubusercontent.com/assets/23268565/20022802/eec8845e-a2e4-11e6-8f3c-3dace98c431d.png)

**Comment by henryyang1993** [comment]
Same problem here for Python3

**Comment by guyoh** [comment]
But I'm using 2.7...

**Comment by noblerwe** [comment]
Did you see any errors during the pip install, missing dependency for example?
I tried to reproduce on a clean mac with scipy installed and did not see a problem.

Please provide more information and reopen.
